services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: employees
    healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U employees -d employees'" ]
  employees-python:
    image: employee-python-cicd
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "81:5000"
    environment:
      DATABASE_HOST: postgres
#    healthcheck:
#      test: curl --fail http://localhost:5000 | exit 1
#      interval: 5s
#      retries: 3
#      timeout: 30s

  api-test:
    profiles:
      - api-test
    image: employees-python-test
    depends_on:
      employees-python:
        condition: service_healthy
    environment:
      EMPLOYEES_URL: http://employees-python:5000/
    command: python -m pytest -v test/e2e/test_employees_api.py

  selenium-hub:
    profiles:
      - ui-test
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      # https://github.com/SeleniumHQ/docker-selenium/issues/2355
      SE_ENABLE_TRACING: false

  chrome:
    profiles:
      - ui-test
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_ENABLE_TRACING: false
    expose:
      - "5900"
    privileged: true

  chrome-video:
    profiles:
      - ui-test
    image: selenium/video
    volumes:
      - ./videos:/videos
    depends_on:
      - chrome
    environment:
      DISPLAY_CONTAINER_NAME: chrome
      FILE_NAME: chrome-video.mp4

  ui-test:
    profiles:
      - ui-test
    image: employees-python-test
    depends_on:
      employees-python:
        condition: service_healthy
    environment:
      EMPLOYEES_URL: http://employees-python:5000/
      SELENIUM_DRIVER: RemoteWebDriver
      SELENIUM_HUB_URL: http://selenium-hub:4444/wd/hub
    command: python -m pytest -v test/e2e/test_employees_ui.py